---
- hosts: all
  become: yes
  tasks:
    - name: Ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest # Changed from 'present' to 'latest'
        update_cache: yes

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Update nginx welcome page
      template:
        src: /tmp/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"
